export const foods = [
  {
    id: 0,
    category: 'Entradas',
    name: 'Ceviche',
    unityPrice: 12,
  },
  {
    id: 1,
    category: 'Entradas',
    name: 'Sunomono',
    unityPrice: 12,
  },
  {
    id: 2,
    category: 'Entradas',
    name: 'Pasta de Atum',
    unityPrice: 8,
  },
  {
    id: 3,
    category: 'Entradas',
    name: 'Carpaccio de Salmão',
    unityPrice: 18,
  },
  {
    id: 4,
    category: 'Entradas',
    name: 'Tartar Crispy',
    unityPrice: 4,
  },
  {
    id: 5,
    category: 'Entradas',
    name: 'Tartar Chips',
    unityPrice: 4,
  },
  {
    id: 6,
    category: 'Entradas Quentes',
    name: 'Guioza',
    unityPrice: 12,
  },
  {
    id: 7,
    category: 'Entradas Quentes',
    name: 'Missoshiro',
    unityPrice: 12,
  },
  {
    id: 8,
    category: 'Entradas Quentes',
    name: 'Lula à dorê',
    unityPrice: 15,
  },
  {
    id: 9,
    category: 'Entradas Quentes',
    name: 'Nuvem Philadelphia Crocante',
    unityPrice: 10,
  },
  {
    id: 10,
    category: 'Entradas Quentes',
    name: 'Bolinho de Salmão',
    unityPrice: 4,
  },
  {
    id: 11,
    category: 'Entradas Quentes',
    name: 'Tempura Mix',
    unityPrice: 8,
  },
  {
    id: 12,
    category: 'Entradas Quentes',
    name: 'Shimeji',
    unityPrice: 12,
  },
  {
    id: 13,
    category: 'Harumaki',
    name: 'Legumes',
    unityPrice: 4.75,
  },
  {
    id: 14,
    category: 'Harumaki',
    name: 'Camarão',
    unityPrice: 6,
  },
  {
    id: 15,
    category: 'Harumaki',
    name: 'Queijo',
    unityPrice: 5.25,
  },
  {
    id: 16,
    category: 'Harumaki',
    name: 'Salmão',
    unityPrice: 6,
  },
  {
    id: 17,
    category: 'Sashimi',
    name: 'Atum',
    unityPrice: 3.6,
  },
  {
    id: 18,
    category: 'Sashimi',
    name: 'Peixe Branco',
    unityPrice: 3.6,
  },
  {
    id: 19,
    category: 'Sashimi',
    name: 'Polvo',
    unityPrice: 3.7,
  },
  {
    id: 20,
    category: 'Sashimi',
    name: 'Haddock',
    unityPrice: 4,
  },
  {
    id: 21,
    category: 'Sashimi',
    name: 'Salmão Roasted',
    unityPrice: 3.8,
  },
  {
    id: 22,
    category: 'Sashimi',
    name: 'Salmão Luxo',
    unityPrice: 4,
  },
  {
    id: 23,
    category: 'Sashimi',
    name: 'Salmão Maracujá',
    unityPrice: 3.9,
  },
  {
    id: 24,
    category: 'Sashimi',
    name: 'Salmão Crispy',
    unityPrice: 4,
  },
  {
    id: 25,
    category: 'Sashimi',
    name: 'Salmão na Crosta',
    unityPrice: 3.9,
  },
  {
    id: 26,
    category: 'Sashimi',
    name: 'Salmão Trufado',
    unityPrice: 4.1,
  },
  {
    id: 27,
    category: 'Sashimi',
    name: 'Atum Roasted',
    unityPrice: 3.7,
  },
  {
    id: 28,
    category: 'Joe',
    name: 'Tradicional',
    unityPrice: 5.75,
  },
  {
    id: 29,
    category: 'Joe',
    name: 'Camarão',
    unityPrice: 6.75,
  },
  {
    id: 30,
    category: 'Joe',
    name: 'Maracujá',
    unityPrice: 6.25,
  },
  {
    id: 31,
    category: 'Joe',
    name: 'Abacaxi',
    unityPrice: 6.25,
  },
  {
    id: 32,
    category: 'Joe',
    name: 'Amora',
    unityPrice: 6.25,
  },
  {
    id: 33,
    category: 'Joe',
    name: 'Lemon',
    unityPrice: 6.25,
  },
  {
    id: 34,
    category: 'Joe',
    name: 'Crispy',
    unityPrice: 6.5,
  },
  {
    id: 35,
    category: 'Joe',
    name: 'Spicy',
    unityPrice: 6.25,
  },
  {
    id: 36,
    category: 'Joe',
    name: 'Roasted',
    unityPrice: 6.5,
  },
  {
    id: 37,
    category: 'Sushi',
    name: 'Salmão',
    unityPrice: 5.5,
  },
  {
    id: 38,
    category: 'Sushi',
    name: 'Atum',
    unityPrice: 5,
  },
  {
    id: 39,
    category: 'Sushi',
    name: 'Peixe Branco',
    unityPrice: 5,
  },
  {
    id: 40,
    category: 'Sushi',
    name: 'Polvo',
    unityPrice: 6,
  },
  {
    id: 41,
    category: 'Sushi',
    name: 'Camarão',
    unityPrice: 6,
  },
  {
    id: 42,
    category: 'Sushi',
    name: 'Salmão Skin',
    unityPrice: 4.5,
  },
  {
    id: 43,
    category: 'Sushi',
    name: 'Salmão Roasted',
    unityPrice: 6,
  },
  {
    id: 44,
    category: 'Sushi',
    name: 'Atum Roasted',
    unityPrice: 5.5,
  },
  {
    id: 45,
    category: 'Sushi',
    name: 'Salmão Cheese',
    unityPrice: 6,
  },
  {
    id: 46,
    category: 'Sushi',
    name: 'Salmão Trufado',
    unityPrice: 6.5,
  },
  {
    id: 47,
    category: 'Makimono Roll',
    name: 'Philadelphia',
    unityPrice: 3,
  },
  {
    id: 48,
    category: 'Makimono Roll',
    name: 'Philadelphia Crocante',
    unityPrice: 2.4,
  },
  {
    id: 49,
    category: 'Makimono Roll',
    name: 'California',
    unityPrice: 2.6,
  },
  {
    id: 50,
    category: 'Makimono Roll',
    name: 'Boston Cheese',
    unityPrice: 2.4,
  },
  {
    id: 51,
    category: 'Makimono Roll',
    name: 'Uramaki Salmão',
    unityPrice: 3.2,
  },
  {
    id: 52,
    category: 'Makimono Roll',
    name: 'Uramaki Crispy',
    unityPrice: 2.4,
  },
  {
    id: 53,
    category: 'Makimono Roll',
    name: 'Uramaki Atum',
    unityPrice: 2.4,
  },
  {
    id: 54,
    category: 'Makimono Roll',
    name: 'Uramaki Skin',
    unityPrice: 2.4,
  },
  {
    id: 55,
    category: 'Makimono Roll',
    name: 'Spicy Tuna',
    unityPrice: 3,
  },
  {
    id: 56,
    category: 'Hot Roll',
    name: 'Philadelphia',
    unityPrice: 2.8,
  },
  {
    id: 57,
    category: 'Hot Roll',
    name: 'Philadelphia Crocante',
    unityPrice: 2.9,
  },
  {
    id: 58,
    category: 'Hot Roll',
    name: 'Philadelphia Abacaxi',
    unityPrice: 2.9,
  },
  {
    id: 59,
    category: 'Hot Roll',
    name: 'Philadelphia Tartar',
    unityPrice: 2.9,
  },
  {
    id: 60,
    category: 'Hot Roll',
    name: 'Philadelphia Crispy',
    unityPrice: 2.9,
  },
  {
    id: 61,
    category: 'Hot Roll',
    name: 'Philadelphia Spicy',
    unityPrice: 2.9,
  },
  {
    id: 62,
    category: 'Hot Roll',
    name: 'Camarão',
    unityPrice: 3,
  },
  {
    id: 63,
    category: 'Hot Roll',
    name: 'Haddock Croc',
    unityPrice: 2.9,
  },
  {
    id: 64,
    category: 'Hot Roll',
    name: 'Haru',
    unityPrice: 2.9,
  },
  {
    id: 65,
    category: 'Hot Roll',
    name: 'Haru Skin',
    unityPrice: 2.8,
  },
  {
    id: 66,
    category: 'Temaki',
    name: 'Philadelphia',
    unityPrice: 14.5,
  },
  {
    id: 676,
    category: 'Temaki',
    name: 'Salmão Crispy',
    unityPrice: 16.5,
  },
  {
    id: 68,
    category: 'Temaki',
    name: 'Atum',
    unityPrice: 13.5,
  },
  {
    id: 69,
    category: 'Temaki',
    name: 'Atum Temperado',
    unityPrice: 14.5,
  },
  {
    id: 70,
    category: 'Temaki',
    name: 'Camarão',
    unityPrice: 15,
  },
  {
    id: 71,
    category: 'Temaki',
    name: 'Camarão Crispy',
    unityPrice: 17,
  },
  {
    id: 72,
    category: 'Temaki',
    name: 'California',
    unityPrice: 13.5,
  },
  {
    id: 73,
    category: 'Temaki',
    name: 'Philadelphia Hot',
    unityPrice: 15.5,
  },
  {
    id: 74,
    category: 'Temaki',
    name: 'Hot Crocante',
    unityPrice: 15,
  },
];
